exports.seed = async function seed(knex){
    await knex('category').insert([
        { title:'Pedreiro'},
        { title:'Doméstico'},
        { title:'Agricultura'},
        { title:'Animais'},
        { title:'Arquitetura'},
        { title:'Automóveis'},
        { title:'Caridade'},
        { title:'Comida & Bebida'},
        { title:'Comunicações'},
        { title:'Construção & Ferramentas'},
        { title:'Crianças & Cuidados'},
        { title:'Idosos cuidados'},
        { title:'Automóveis'},
        { title:'Educação'},
        { title:'Encontros'},
        { title:'Entretenimento'},
        { title:'Esportes'},
        { title:'Floral'},
        { title:'Fotografia'},
        { title:'Hospital & Farmácia'},
        { title:'Indústrias'},
        { title:'Internet'},
        { title:'Jogos & Recreação'},
        { title:'Limpeza'},
        { title:'Manutenção'},
        { title:'Meio Ambiente'},
        { title:'Moda & Beleza'},
        { title:'Móvis'},
        { title:'Negócios & Consultoria'},
        { title:'Paisagismo'},
        { title:'Política'},
        { title:'Religiosidade'},
        { title:'Serviços de Noiva'},
        { title:'Spa & Estética'},
        { title:'Tecnologia'},
        { title:'Vendas'},
        { title:'Viagens & Hoteis'},
    ]);
}
