exports.seed = async function seed(knex){
    await knex('categories').insert([
        { id:1, title:'Pedreiro'},
        { id:2, title:'Doméstico'},
        { id:3, title:'Agricultura'},
        { id:4, title:'Animais'},
        { id:5, title:'Arquitetura'},
        { id:6, title:'Automóveis'},
        { id:7, title:'Caridade'},
        { id:8, title:'Comida & Bebida'},
        { id:9, title:'Comunicações'},
        { id:10, title:'Construção & Ferramentas'},
        { id:11, title:'Crianças & Cuidados'},
        { id:12, title:'Idosos cuidados'},
        { id:13, title:'Automóveis'},
        { id:14, title:'Educação'},
        { id:15, title:'Encontros'},
        { id:16, title:'Entretenimento'},
        { id:17, title:'Esportes'},
        { id:18, title:'Floral'},
        { id:19, title:'Fotografia'},
        { id:20, title:'Hospital & Farmácia'},
        { id:21, title:'Indústrias'},
        { id:22, title:'Internet'},
        { id:23, title:'Jogos & Recreação'},
        { id:24, title:'Limpeza'},
        { id:25, title:'Manutenção'},
        { id:26, title:'Meio Ambiente'},
        { id:27, title:'Moda & Beleza'},
        { id:28, title:'Móvis'},
        { id:29, title:'Negócios & Consultoria'},
        { id:30, title:'Paisagismo'},
        { id:31, title:'Política'},
        { id:32, title:'Religiosidade'},
        { id:33, title:'Serviços de Noiva'},
        { id:34, title:'Spa & Estética'},
        { id:35, title:'Tecnologia'},
        { id:36, title:'Vendas'},
        { id:37, title:'Viagens & Hoteis'},
    ]);
}
