exports.seed = async function seed(knex){
    await knex('category').insert([
        { title:'Pedreiro', id:1 },
        { title:'Doméstico', id:2 },
        { title:'Agricultura', id:3 },
        { title:'Animais', id:4 },
        { title:'Arquitetura', id:5 },
        { title:'Automóveis', id:6 },
        { title:'Caridade', id:7 },
        { title:'Comida & Bebida', id:8 },
        { title:'Comunicações', id:9 },
        { title:'Construção & Ferramentas', id:10 },
        { title:'Crianças & Cuidados', id:11 },
        { title:'Idosos cuidados', id:12 },
        { title:'Automóveis', id:13 },
        { title:'Educação', id:14 },
        { title:'Encontros', id:15 },
        { title:'Entretenimento', id:16 },
        { title:'Esportes', id:17 },
        { title:'Floral', id:18 },
        { title:'Fotografia', id:19 },
        { title:'Hospital & Farmácia', id:20 },
        { title:'Indústrias', id:21 },
        { title:'Internet', id:22 },
        { title:'Jogos & Recreação', id:23 },
        { title:'Limpeza', id:24 },
        { title:'Manutenção', id:25 },
        { title:'Meio Ambiente', id:26 },
        { title:'Moda & Beleza', id:27 },
        { title:'Móvis', id:28 },
        { title:'Negócios & Consultoria', id:29 },
        { title:'Paisagismo', id:30 },
        { title:'Política', id:31 },
        { title:'Religiosidade', id:32 },
        { title:'Serviços de Noiva', id:33 },
        { title:'Spa & Estética', id:34 },
        { title:'Tecnologia', id:35 },
        { title:'Vendas', id:36 },
        { title:'Viagens & Hoteis', id:37 },
    ]);
}
